{% set name = "reactivex" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reactivex-{{ version }}.tar.gz
  sha256: e912e6591022ab9176df8348a653fe8c8fa7a301f26f9931c9d8c78a650e04e8

build:
  noarch: python
  # noarch: only build on linux64
  skip: true # [not linux64]

  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
    - wheel
  run:
    - python >=3.7,<4.0
    - typing-extensions >=4.1.1, <5.0.0

test:
  imports:
    - reactivex
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://reactivex.io
  summary: ReactiveX (Rx) for Python
  license: MIT
  license_file: LICENSE

extra:
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url
    - avoid_noarch

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  recipe-maintainers:
    - ruben-arts
  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/44101
    reason: "needed for influxdb-client"
    recipe-maintainers:
      - bkreider

